name: Deploy to Stage
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying entire thing to staging
    runs-on: ubuntu-latest

    steps:
      - name: SSH Into the machine and deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd pipelines
            git pull origin main
            pnpm install
            pnpm run build

            cd apps/http/dist
            pm2 delete http-server || true
            pm2 start index.js --name "http-server"

            cd ../../ws/dist
            pm2 delete ws-server || true
            pm2 start index.js --name "ws-server"

            cd ../../web
            pm2 delete next-app || true
            pm2 start "npm run dev" --name "next-app"
